services:
  - type: web
    name: lyriclens-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GENIUS_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    plan: free
    region: oregon
    autoDeploy: true
    build:
      context: backend